#!/usr/bin/env python3
"""
hybrid_simulation_helper.py
============================
Replaces opencor_helper.SimulationHelper for DAE models where OpenCOR's
CVODES linear solver fails with:
    "the linear solver's setup function failed in an unrecoverable manner"

Root cause of that error:
    CVODES/IDA tries to factorise the full DAE Jacobian, which includes the
    circular algebraic block:
        flow → resistance → viscosity → H_mean → RBC_volume → FQB → flow
    This block's Jacobian is dense and ill-conditioned, so IDA's LU
    factorisation fails.

Fix:
    1.  scipy.integrate.solve_ivp(method='BDF') handles the ODE states.
        This is the same BDF algorithm as CVODES — just Python-callable.
    2.  scipy.optimize.root replaces rootfind_0 inside computeRates.
        It solves the 61-variable iterative algebraic system BEFORE the
        ODE solver ever tries to touch it, so the Jacobian CVODES sees
        is clean.

API mirrors opencor_helper.SimulationHelper so the calling code in
PP_VP_VV_PP_PP.py / run_B1_I.py needs minimal changes.
"""

import sys
import time
import warnings
import importlib.util
from pathlib import Path

import numpy as np
from scipy.integrate import solve_ivp
from scipy.optimize  import root


# ══════════════════════════════════════════════════════════════════════════════
# Variable-name → algebraic/state index map
# Add entries here whenever you need to access a new output variable.
# Keys match the OpenCOR "component/variable" naming convention.
# ══════════════════════════════════════════════════════════════════════════════
ALGEBRAIC_NAME_MAP = {
    # PP capillary (inlet)
    "inlet/H_mean":         39,
    "inlet/v":              45,
    "inlet/u_mmHg":          5,
    "inlet/H_L_out":        36,
    "inlet/H_R_out":        37,

    # VV junction
    "VV_junc1/H_VV_out_alpha": 192,
    "VV_junc1/H_VV_out_beta":  193,
    "VV_junc1/H_mean":           6,
    "VV_junc1/RBC_in":         210,
    "VV_junc1/RBC_out":        211,
    "VV_junc1/v":               11,

    # PV1 pericyte
    "PV1/H_mean":           52,
    "PV1/v":                58,
    "PV1/H_L_out":          49,
    "PV1/H_R_out":          50,

    # PV2 pericyte
    "PV2/H_mean":           65,
    "PV2/v":                71,
    "PV2/H_L_out":          62,
    "PV2/H_R_out":          63,

    # V1 venule
    "V1/H_mean":            77,
    "V1/v":                 83,

    # V2 venule
    "V2/H_mean":            88,
    "V2/v":                 94,
}

STATE_NAME_MAP = {
    # PP capillary states
    "inlet/H_link_R":        0,
    "inlet/H_link_L":        1,
    "inlet/H_down":          2,
    "inlet/q_C":             3,

    # VV junction states
    "VV_junc1/RBC_volume":   4,
    "VV_junc1/q_C":          5,
    "VV_junc1/q_C_d":        6,

    # PV1 states
    "PV1/H_link_R":          7,
    "PV1/H_link_L":          8,
    "PV1/H_down":            9,
    "PV1/q_C":              10,

    # PV2 states
    "PV2/H_link_R":         11,
    "PV2/H_link_L":         12,
    "PV2/H_down":           13,
    "PV2/q_C":              14,

    # V1 states
    "V1/H_link_R":          15,
    "V1/H_link_L":          16,
    "V1/H_down":            17,
    "V1/q_C":               18,

    # V2 states
    "V2/H_link_R":          19,
    "V2/H_link_L":          20,
    "V2/H_down":            21,
    "V2/q_C":               22,
}


# ══════════════════════════════════════════════════════════════════════════════
class HybridSimulationHelper:
    """
    Drop-in replacement for opencor_helper.SimulationHelper.

    Parameters
    ----------
    model_py_path : str | Path
        Path to the Python model file generated by OpenCOR/CellML
        (e.g. B1_I.py).  Must contain initConsts, computeRates,
        computeAlgebraic, residualSN_0.
    dt : float
        Output time interval (seconds) — same as SimulationHelper.
    sim_time : float
        Length of simulation (seconds).
    solver_info : dict, optional
        Recognised keys (mirrors OpenCOR):
            "MaximumStep"          → max_step for BDF solver
            "MaximumNumberOfSteps" → max_step count (used as nsteps hint)
            "AbsoluteTolerance"    → atol  (default 1e-6)
            "RelativeTolerance"    → rtol  (default 1e-6)
            "RootMethod"           → scipy.optimize.root method
                                     'lm' (Levenberg-Marquardt, default)
                                     'hybr' (same as fsolve / MINPACK)
            "RootTolerance"        → tol for root solver (default 1e-6)
    pre_time : float
        Warm-up time before storing results (discarded).
    """

    def __init__(self, model_py_path, dt, sim_time,
                 solver_info=None, pre_time=0.0):

        self.model_py_path = Path(model_py_path)
        self.dt            = dt
        self.sim_time      = sim_time
        self.pre_time      = pre_time
        self._start_time   = 0.0

        # ── load solver settings ─────────────────────────────────────────────
        si = solver_info or {}
        self._max_step    = si.get("MaximumStep",          1.0)
        self._atol        = si.get("AbsoluteTolerance",    1e-6)
        self._rtol        = si.get("RelativeTolerance",    1e-6)
        self._root_method = si.get("RootMethod",           "lm")
        self._root_tol    = si.get("RootTolerance",        1e-6)

        # ── dynamically import the generated model ────────────────────────────
        spec = importlib.util.spec_from_file_location(
            "cellml_model", str(self.model_py_path))
        mod  = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        self._mod = mod

        # ── fix numpy 1.24+ incompatibility in auto-generated CellML code ────
        # B1_I.py calls vstack(a, b) with two positional args.
        # numpy >= 1.24 requires vstack([a, b]).
        # Patch the name in the module namespace — no need to edit B1_I.py.
        import numpy as _np
        _orig_vstack = _np.vstack
        def _vstack_compat(*args):
            if len(args) == 1:
                return _orig_vstack(args[0])
            return _orig_vstack(args)
        mod.vstack = _vstack_compat

        # pull the four functions we need
        self._initConsts       = mod.initConsts
        self._computeRates     = mod.computeRates
        self._computeAlgebraic = mod.computeAlgebraic
        self._residualSN_0     = mod.residualSN_0

        # ── internal state ───────────────────────────────────────────────────
        self._init_states  = None
        self._constants    = None
        self._states_hist  = None   # shape (n_states, n_timepoints)
        self._algebraic_hist = None # shape (n_alg,   n_timepoints)
        self._t_hist       = None

        self._root_x0      = None   # warm-start for root solver
        self._last_wall_time = None

        self._initialise()

    # ──────────────────────────────────────────────────────────────────────────
    def _initialise(self):
        init_states, constants = self._initConsts()
        self._init_states = np.array(init_states, dtype=float)
        self._constants   = constants
        self._root_x0     = np.ones(61) * 0.1   # initial guess for root

    # ──────────────────────────────────────────────────────────────────────────
    def _rootfind_scipy(self, voi, constants, rates, states, algebraic):
        """
        Replaces rootfind_0: solves the 61-variable iterative algebraic
        system with scipy.optimize.root instead of OpenCOR's levmar /
        fsolve. Writes solution back into `algebraic` in-place.

        The 61 unknowns are algebraic[34] … algebraic[94].
        They encode the per-vessel coupled loop:
            w_v / w_v_d  (flow direction weights)
            → v / v_d    (Poiseuille volumetric flow)
            → R          (Hagen-Poiseuille resistance)
            → mu         (haematocrit-dependent viscosity)
            → H_mean     (mean haematocrit)
            → RBC_volume (RBC conservation)
            → FQB_alpha  (Pries et al. splitting fraction)
            ↩ back to v / v_d
        """
        result = root(
            self._residualSN_0,
            self._root_x0,
            args=(algebraic, voi, constants, rates, states),
            method=self._root_method,
            tol=self._root_tol,
        )

        if not result.success:
            warnings.warn(
                f"scipy.optimize.root did not converge at t={voi:.4f} "
                f"[{self._root_method}]: {result.message}",
                RuntimeWarning, stacklevel=3,
            )

        soln = result.x
        self._root_x0 = soln  # warm-start next call

        # write the 61 solved values back into algebraic[34:95]
        for k, idx in enumerate(range(34, 95)):
            algebraic[idx] = soln[k]

    # ──────────────────────────────────────────────────────────────────────────
    def _rates_rhs(self, t, y):
        """
        Right-hand side passed to scipy.integrate.solve_ivp.
        Calls computeRates after redirecting rootfind_0 to our scipy version.
        """
        # temporarily swap rootfind_0 in the imported module
        orig            = self._mod.rootfind_0
        self._mod.rootfind_0 = self._rootfind_scipy
        try:
            rates = self._computeRates(t, list(y), self._constants)
        finally:
            self._mod.rootfind_0 = orig   # always restore

        return np.array(rates, dtype=float)

    # ──────────────────────────────────────────────────────────────────────────
    def reset_and_clear(self):
        """Mirror of SimulationHelper.reset_and_clear()."""
        self._initialise()
        self._states_hist    = None
        self._algebraic_hist = None
        self._t_hist         = None
        self._last_wall_time = None

    def reset_states(self):
        """Mirror of SimulationHelper.reset_states()."""
        init_states, _ = self._initConsts()
        self._init_states = np.array(init_states, dtype=float)
        self._root_x0 = np.ones(61) * 0.1

    def update_times(self, dt, start_time, sim_time, pre_time):
        """Mirror of SimulationHelper.update_times()."""
        self.dt          = dt
        self._start_time = start_time
        self.sim_time    = sim_time
        self.pre_time    = pre_time

    # ──────────────────────────────────────────────────────────────────────────
    def run(self):
        """
        Integrate the model.  Wall time (integration only) is stored in
        self.last_wall_time.  Returns True on success, False on failure
        (same convention as SimulationHelper).
        """
        total_end   = self._start_time + self.pre_time + self.sim_time
        store_start = self._start_time + self.pre_time

        # dense output points for stored results
        n_pts  = max(2, int(self.sim_time / self.dt) + 1)
        t_store = np.linspace(store_start, total_end, n_pts)

        # all evaluation points (include pre-time)
        if self.pre_time > 0:
            n_pre   = max(2, int(self.pre_time / self.dt) + 1)
            t_pre   = np.linspace(self._start_time, store_start, n_pre)
            t_eval  = np.unique(np.concatenate([t_pre, t_store]))
        else:
            t_eval = t_store

        t_span = (t_eval[0], t_eval[-1])

        t0_wall = time.perf_counter()
        try:
            sol = solve_ivp(
                self._rates_rhs,
                t_span,
                self._init_states,
                method="BDF",          # same algorithm as OpenCOR's CVODES
                t_eval=t_eval,
                rtol=self._rtol,
                atol=self._atol,
                max_step=self._max_step,
                dense_output=False,
            )
        except Exception as exc:
            warnings.warn(f"solve_ivp failed: {exc}", RuntimeWarning, stacklevel=2)
            self._last_wall_time = time.perf_counter() - t0_wall
            return False

        self._last_wall_time = time.perf_counter() - t0_wall

        if not sol.success:
            warnings.warn(f"solve_ivp did not succeed: {sol.message}",
                          RuntimeWarning, stacklevel=2)
            return False

        # keep only the stored (post-pre_time) portion
        mask            = sol.t >= store_start - 1e-12
        self._t_hist    = sol.t[mask]
        states_stored   = sol.y[:, mask]   # shape (n_states, n_stored)

        # compute full algebraic array for every stored time point
        self._states_hist    = states_stored
        self._algebraic_hist = self._computeAlgebraic(
            self._constants, states_stored, self._t_hist)

        return True

    # ──────────────────────────────────────────────────────────────────────────
    def get_results(self, variables_list, flatten=False):
        """
        Mirror of SimulationHelper.get_results().

        Parameters
        ----------
        variables_list : list of str
            Each entry is either 'time' or a 'component/variable' name
            from ALGEBRAIC_NAME_MAP / STATE_NAME_MAP.
        flatten : bool
            If True, return a flat list rather than list-of-lists.

        Returns
        -------
        list of list, matching SimulationHelper's format.
        """
        if self._t_hist is None:
            raise RuntimeError("Call run() before get_results().")

        # normalise: each entry becomes a list (same as SimulationHelper)
        if not isinstance(variables_list[0], list):
            variables_list = [[v] for v in variables_list]

        results = []
        for var_group in variables_list:
            group_result = []
            for var in var_group:
                if var == "time":
                    group_result.append(self._t_hist.copy())
                elif var in ALGEBRAIC_NAME_MAP:
                    idx = ALGEBRAIC_NAME_MAP[var]
                    group_result.append(self._algebraic_hist[idx].copy())
                elif var in STATE_NAME_MAP:
                    idx = STATE_NAME_MAP[var]
                    group_result.append(self._states_hist[idx].copy())
                else:
                    available = (list(ALGEBRAIC_NAME_MAP.keys())
                                 + list(STATE_NAME_MAP.keys())
                                 + ["time"])
                    raise KeyError(
                        f"Variable '{var}' not found.\n"
                        f"Available variables:\n"
                        + "\n".join(f"  {n}" for n in sorted(available))
                    )
            results.append(group_result)

        if flatten:
            return [item for sub in results for item in sub]
        return results

    # ──────────────────────────────────────────────────────────────────────────
    @property
    def last_wall_time(self):
        """Wall time (seconds) of the most recent run() call."""
        return self._last_wall_time

    def close_simulation(self):
        """No-op: mirrors SimulationHelper.close_simulation()."""
        pass
